os:
- linux
- osx

language: rust

rust:
- stable
- nightly

cache:
  timeout: 1000
  cargo: true

before_cache:
- rm -rf target

script:
- cargo build --all
- cargo test --all
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true

